const stage1 = [
"                             M                                           fffffffffffffffffffffffffffffffffff                            ",
"                  LLLLL      M                                                                                                          ",
"                             M                                                                                                          ",
"                         LLL M            =O==OO                  C                                                                           ",
"                                       X X=OX==@                                            ff               =====                        ",
"          LLLLL               ===     XCCCCCCCCC^^^^^^^^^^@==~---O                     ff                                                  ",
"                   A                %%*%%%%####@@^^^^@@@===%==#Q%---                FF                                                          ",
"                C  A                X##X##G%%%%#@@@@@CCC      %%%%QQQQQ       ff                                                            ",
"         LLL       A                %%%G%%%#W##%G%%X#*##C    #*###%QQ                                                                           ",
"                                     X#####W#*####X#G#*#    %% #       %      ~%                                                                 ",
" P   s J !  j *                ==    X#***%XX             * # C#  CC%OOOO%CCC%~~~~~%X                   ========                                 ",
"OOO~~OO @X^^^XX@ S    BBBB    ===              *#%     %%%%    X   X----=-XXXXX~ ~~~                                                                ",
"==---##  @X@XXX@X@                             #*##%%%%XXXXX  XXX    X==X=XX   ~  ~~                                                               ",
"XXXX%%     @  X X          C             X#   ##W###G###              X%XX%X      ~~                                                              ",
"                                       XOOOX#%%%%W%%%%%X@^^^@^@^^   XCCCC         ~                                                                  ",
"                                 OOOO    X--X####G#X#####@@^^^^^^^@^XXX%X                                  C                                 ",
"                A        T###T  O--~~~~-    AXX###XXXX##XXX@^^^^^^^^@XX                                                                   ",
"                A      T==%%%# O-==~@@X=@   A  V====X=#=X~~~@@@@@@@@X                                                                             ",
"            A ! A !    =*~~~~=   X@~ @*X    A  V    X===C   XXXXXX~X                                                                       ",
" =====      A WWWWW   #%%%%%%=#   ~~      ! A  V                                                                                        ",
"            ##MMMMMW! =+##*~+#V   ~       +<+  V A                                                          OO                          ",
"         ! !#M<K<<<KW == V#%=YV      %   +WWW+ V A                                ====                    O-----                        ",
"       !WWWWM<<<<<<MX Y  V == V C   % %  Y+<+V V A!                         j                            --=`?`?==OO                    ",
"      #WKMMM<<<<<<MMX   #V #= V     #     V  Y +<<+                     WWWWWWW                  s    -O-=?`?`?`??=--                   ",
"      #M<<<<K<<<KMXX#  # #  # V !   X   A V  <<#C##+                    =XXXX#=                OOO s  ??????H??????                      ",
"      #M<<<<<<MMX# V   # Y  Y   X  !WW TA V +#####+V      C             Y=##= V              XX*--X=X***XOXXX?????               ",
"      ##KM<MMKXXX# V#  O      WWXTOW**WOO   YY+WWW          j            = Y V          X s         XXXXXXXXXXXXX                  ",
"      V #XMXXXXX#V V# XRW%%%%WXQOO+++**WO     V  V       %%%%%%%       !( V             XXOO*XXCCCCCCCCCCCC  XXX                   ",
"      V   ## #X# V     X=====#OO**CCC+*XOT       V  %%%           A   A(X(V          X****XXXXOOOXX*XX        X                ",
"      V #    V## V  #   XXQX#OO*CCCCCCC*WO                 A  !  A A  AX#(V              XXX  ----  XXXX                        ",
"      V V    V#  V  V    ####### CCCCC+*XO               ! ((((  A   !X##X(                    ==     XXX     X ========         ",
"      V V  # V   V  V            CCCCC*WO       II      (((XXXX((A   (X###(f             X X          XXX                               ",
"      V V        V              O*CC+**OO    >>I>>>>I   LXX####XX(   (#G##Lf               X       X   X                                ",
"      V V                       OX***WWO    I**>>>I*     LLL#G##X( !(X###?Xf                       XX XX                                ",
"      V                          YOOOOO      I ***I         LL###X((X####C#                         XXX                                ",
"                                             I II     %!      ##G#XX##G##C#      =======                                               ",
"                                               I  I  %#%      L##########*#!                                                            ",
"                                               I     LLL       LL#G#####OO#(                         =======================          ======= ",
"   M  MMMM                                               !       LLLL###~~~X                    T                C            = ",
"   MCCCCCM                           M         C        K#### !      L~~~~~#            !      OW                             = ",
"   MCCCCCM    <<<<<      >>>>>>>>    M               LL#@@@#~###LL    L~~~~L            WOOTWOW-X  +++                        = ",
"   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        =====LL !#@^^#~~C        LOOL             W-WW--X##  +++                        = ",
"                                                YY    #@^^^####    O          ---    LLL GXXR=#             ff                         = ",
"                                      !!              K@@@@K       -    --=%===%= LLL     ####           ff                            = ",
"                                      OOO              #R##       O=   %X=RX=XR==#                    ff                               = ",
"                                     --+=O                        -=O  QRX==X=X=#V                 ff         ==========                = ",
"       %%%   CCCCCCCCC%%              X##-                       O==-LLVQ=QRX#R# V                                                     = ",
"     %%XXX%%%%%%%%%%%%##%%         !   # Y                       -===  V Y ##=## V             OO+                                     = ",
"      ##XXX########XX  ###        OO T V                         =+==      V##V               O-----OOO+                                = ",
"           XXXX##XX     X        O--OO                           ===XX     V VV        j    OO=====+----OO                             = ",
"                                 -==+-         ss ====         XX%==##X      VV     ==+=+OOO--==+X======XX+                             = ",
"                                 VYX#       ==OOOO==XQX`` ???` `XX=X###X      V     Y -----=====XXX==+XXXX+#      =========                 = ",
"                                 V  V         =====##X ?? ?? ??  ??=X##XX     V          =+==+=XX# XXXXXXX##                              = ",
"                       *****        V         =  ===== X%X     ??XXXX###XQX   V           ==XXXX#  #+#+####                               = ",
"     I C I            *XXXXX*I                =   Y  =              XQ##***QX V    O      Y ####   ###+#                                  = ",
"=     *?*             *XII**IIII             =       =%%       C    XX#*CCCC*XX   O-O               #+#                                   = ",
"=    C?C?C          **XII*XXXXIIIII          Y   OOOOXQX      CCC    XX*CCCCCC*X  O=O               ###                                   = ",
"==    I?I          *%XXXXX*X**XXIIII            ----XXXXX    CCCCC    X#*CCCCC*X  O=-O   OO          #                                    = ",
"===  * C *        **%%%%%%%*XX**X**II        ---===###X     CCCCCCC   X##*CC   X  O==-OOO--OO                                             = ",
"====>>>>I>III>I>>>*########%XXXX*XX*I    ----===########   CCCCCCCCC XQ##XQ*   Y O-===---==--OCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC ======== ",
"========================================================================================================================================"
]

const stage2 = []
